server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: ${my.app.port:10000}
spring:
  application:
    name: order
  config:
    import: configserver:http://127.0.0.1:8888
turkcell:
  error:
    microservice: order
    bounded-context: order-bc
resilience4j:
  retry:
    instances:
      restaurant-menu-get-price:
        base-config: common-restaurant
        result-predicate: org.turkcell.training.spring.order.integration.resiliency.RestaurantMenuGetPriceResponseChecher
      restaurant-menu-get-price2:
        base-config: common-restaurant
      restaurant-menu-get-price-feign:
        base-config: common-restaurant
        result-predicate: org.turkcell.training.spring.order.integration.resiliency.RestaurantMenuGetPriceResponseChecher
    configs:
      common-restaurant:
        max-attempts: 3
        wait-duration: 2ms
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 5ms
        enable-exponential-backoff: true
        retry-exception-predicate: org.turkcell.training.spring.order.integration.resiliency.RestaurantMenuGetPriceRetryChooser
  circuitbreaker:
    instances:
      restaurant-menu-get-price-cb:
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 1s
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 500ms

